project:
  type: website
  output-dir: docs

website:
  title: "SPT Dataset"
  navbar:
    background: #426d58
    title: false
    search: true 
    left:
      - href: index.qmd
        text: Home
      - href: datavis.qmd
        text: Data Visualization
      - about.qmd

format:
  html:
    theme:
      - lux
      - brand
    max-width: 1200px
    css: styles.css
    toc: false
